package com.flippey.qrdemo.utils;

import java.util.HashMap;
import java.util.Map;

public class XidiFonts {
    private Map<String, String> countryIconMap;

    public Map<String, String> getCountryMap() {
        destroyCountryMap();
        countryIconMap = new HashMap<String, String>();
        countryIconMap.put("036", "\ue800");
        countryIconMap.put("040", "\ue801");
        countryIconMap.put("056", "\ue802");
        countryIconMap.put("076", "\ue803");
        countryIconMap.put("124", "\ue804");
        countryIconMap.put("208", "\ue805");
        countryIconMap.put("246", "\ue806");
        countryIconMap.put("250", "\ue807");
        countryIconMap.put("276", "\ue808");
        countryIconMap.put("300", "\ue809");
        countryIconMap.put("372", "\ue80a");
        countryIconMap.put("380", "\ue80b");
        countryIconMap.put("392", "\ue80c");
        countryIconMap.put("410", "\ue80d");
        countryIconMap.put("442", "\ue80e");
        countryIconMap.put("528", "\ue80f");
        countryIconMap.put("554", "\ue810");
        countryIconMap.put("578", "\ue811");
        countryIconMap.put("620", "\ue812");
        countryIconMap.put("702", "\ue813");
        countryIconMap.put("724", "\ue814");
        countryIconMap.put("752", "\ue815");
        countryIconMap.put("756", "\ue816");
        countryIconMap.put("792", "\ue817");
        countryIconMap.put("826", "\ue818");
        countryIconMap.put("840", "\ue819");
        return countryIconMap;
    }

    public void destroyCountryMap() {
        if (countryIconMap != null) {
            countryIconMap.clear();
            countryIconMap = null;
        }
    }

    public static final String icon_world_culture_selected = "\ue937";
    public static final String icon_me_selected = "\ue938";
    public static final String icon_faverate_selected_new = "\ue925";
    public static final String icon_faverate_unselected_new = "\ue926";
    public static final String icon_me_unselected = "\ue92b";
    public static final String icon_world_product_selected = "\ue92c";
    public static final String icon_world_product_unselected = "\ue92d";
    public static final String icon_world_life_selected = "\ue92e";
    public static final String icon_world_life_unselected = "\ue92f";
    public static final String icon_world_culture_unselected = "\ue934";
    public static final String icon_more_new = "\ue935";
    public static final String icon_tepin = "\ue936";
    public static final String icon_icon_share_1 = "\ue90c";
    public static final String icon_newshopclass = "\ue90f";
    public static final String icon_newrightarrow = "\ue910";
    public static final String icon_coupon = "\ue90e";

    public static final String icon_mesg = "\ue907";
    public static final String icon_notice = "\ue841";
    public static final String icon_cancel_path1 = "\ue908";
    public static final String icon_cancel_path2 = "\ue909";
    public static final String icon_dalogo = "\ue90a";
    public static final String icon_seven_circle = "\ue90b";
    public static final String icon_share_1 = "\ue90c";
    public static final String icon_thumbnail = "\ue90d";
    public static final String icon_more = "\ue906";
    public static final String icon_info6 = "\ue903";
    public static final String icon_info5 = "\ue904";
    public static final String icon_on_seven_circle = "\ue905";
    public static final String icon_add_circle = "\ue81a";
    public static final String icon_address = "\ue81b";
    public static final String icon_back = "\ue81c";
    public static final String icon_bag = "\ue81d";
    public static final String icon_brand = "\ue81e";
    public static final String icon_uniE81F = "\ue81f";
    public static final String icon_uniE820 = "\ue820";
    public static final String icon_cart_add = "\ue821";
    public static final String icon_cart_empty = "\ue822";
    public static final String icon_cart_full = "\ue823";
    public static final String icon_cart_minus = "\ue824";
    public static final String icon_category = "\ue825";
    public static final String icon_chat = "\ue826";
    public static final String icon_chat2 = "\ue827";
    public static final String icon_clear = "\ue828";
    public static final String icon_close = "\ue829";
    public static final String icon_comment1 = "\ue82a";
    public static final String icon_comment2 = "\ue82b";
    public static final String icon_complete_circle = "\ue82c";
    public static final String icon_copyright = "\ue82d";
    public static final String icon_determine = "\ue82e";
    public static final String icon_di = "\ue82f";
    public static final String icon_edit = "\ue830";
    public static final String icon_edit_complete = "\ue831";
    public static final String icon_favorite = "\ue832";
    public static final String icon_filter = "\ue833";
    public static final String icon_history = "\ue834";
    public static final String icon_home = "\ue835";
    public static final String icon_info1 = "\ue836";
    public static final String icon_info2 = "\ue837";
    public static final String icon_info3 = "\ue838";
    public static final String icon_info4 = "\ue839";
    public static final String icon_listView = "\ue83a";
    public static final String icon_lock = "\ue83b";
    public static final String icon_logo = "\ue83c";
    public static final String icon_logo_bold = "\ue83d";
    public static final String icon_logo_leaf = "\ue83e";
    public static final String icon_mail = "\ue83f";
    public static final String icon_me = "\ue840";
    public static final String icon_other = "\ue842";
    public static final String icon_password_hide = "\ue843";
    public static final String icon_password_show = "\ue844";
    public static final String icon_phone = "\ue845";
    public static final String icon_qq = "\ue846";
    public static final String icon_search = "\ue847";
    public static final String icon_sellout = "\ue848";
    public static final String icon_share_header = "\ue84b";
    public static final String icon_share_qq = "\ue84c";
    public static final String icon_share_qq_weibo = "\ue84d";
    public static final String icon_share_qq_zone = "\ue84e";
    public static final String icon_share_ren = "\ue84f";
    public static final String icon_share_weibo = "\ue850";
    public static final String icon_shop = "\ue851";
    public static final String icon_space_address = "\ue852";
    public static final String icon_space_comment = "\ue853";
    public static final String icon_space_contact = "\ue854";
    public static final String icon_space_express = "\ue855";
    public static final String icon_space_faq = "\ue856";
    public static final String icon_space_favorite = "\ue857";
    public static final String icon_space_feedback = "\ue858";
    public static final String icon_space_order = "\ue859";
    public static final String icon_space_recent = "\ue85a";
    public static final String icon_icons112 = "\ue85b";
    public static final String icon_triangle_down = "\ue85c";
    public static final String icon_triangle_left = "\ue85d";
    public static final String icon_triangle_right = "\ue85e";
    public static final String icon_triangle_up = "\ue85f";
    public static final String icon_unfavorite = "\ue860";
    public static final String icon_unfinished = "\ue861";
    public static final String icon_user = "\ue862";
    public static final String icon_warning = "\ue863";
    public static final String icon_shield = "\ue864";
    public static final String icon_wechat = "\ue865";
    public static final String icon_without_seven_circle = "\ue867";
    public static final String icon_xi = "\ue868";
    public static final String icon_weibo = "\ue869";
    public static final String icon_icons2 = "\ue86a";
    public static final String icon_icons1 = "\ue86b";
    public static final String icon_share = "\ue900";
    public static final String icon_NCHUO = "\ue901";
    public static final String icon_selected = "\ue902";
    public static final String newshopclass = "\ue90f";
    public static final String newwhirearrow = "\ue910";
    public static final String coupon = "\ue90e";
}